### ISSUE TITLE
Refactor validate-authors.py

### ISSUE THREAD

**Issue by kailashchoudhary11** [genicsblog/theme-files#61]
DRY principle can be implemented do reduce code duplication.

**Comment by gouravkhunger** [comment]
Ah yes! I had to setup things & get going quickly so skipped doing improvements 😂
You are welcome to contribute!

Some context: this script is [used for PR checks on drafts](https://github.com/genicsblog/genicsblog.com/blob/main/.github/workflows/validate-authors.yml#L43) to check if authors edit their own drafts, not other's. I didn't add it to that repository because it could have been edited in PRs. Its fetch the raw file from this repo's main branch because that is safer.
